# Generated by Django 5.2.16 on 2026-07-28 06:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whmcs_deptid', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SLAPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('priority', models.CharField(blank=True, help_text='Leave blank to apply to all priorities (e.g. Low/Medium/High/Critical).', max_length=50, null=True)),
                ('first_response_target_minutes', models.PositiveIntegerField()),
                ('resolution_target_minutes', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, help_text='Leave blank to apply to all departments.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sla_policies', to='audit.department')),
            ],
            options={
                'verbose_name_plural': 'SLA policies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whmcs_ticket_id', models.PositiveIntegerField(unique=True)),
                ('tid', models.CharField(blank=True, max_length=50)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(max_length=100)),
                ('priority', models.CharField(blank=True, max_length=50)),
                ('requestor_name', models.CharField(blank=True, max_length=255)),
                ('requestor_email', models.CharField(blank=True, max_length=255)),
                ('opened_at', models.DateTimeField()),
                ('last_reply_at', models.DateTimeField(blank=True, null=True)),
                ('first_response_at', models.DateTimeField(blank=True, help_text='Timestamp of the earliest Operator reply.', null=True)),
                ('closed_at', models.DateTimeField(blank=True, help_text='Set the first time a sync observes status=Closed; may lag real closure by up to one sync interval.', null=True)),
                ('synced_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('first_response_due_at', models.DateTimeField(blank=True, null=True)),
                ('first_response_met', models.BooleanField(blank=True, null=True)),
                ('resolution_due_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_met', models.BooleanField(blank=True, null=True)),
                ('sla_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('at_risk', 'At Risk'), ('breached', 'Breached'), ('met', 'Met')], max_length=20, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='audit.department')),
                ('sla_policy', models.ForeignKey(blank=True, help_text='Snapshot of which policy applied at last evaluation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='audit.slapolicy')),
            ],
            options={
                'ordering': ['-last_reply_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whmcs_reply_id', models.CharField(max_length=50)),
                ('author_name', models.CharField(blank=True, max_length=255)),
                ('author_type', models.CharField(blank=True, max_length=20)),
                ('admin_name', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField(blank=True)),
                ('posted_at', models.DateTimeField()),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_replies', to='audit.ticketsnapshot')),
            ],
            options={
                'ordering': ['posted_at'],
                'unique_together': {('ticket', 'whmcs_reply_id')},
            },
        ),
    ]
