# Generated by Django 5.2.16 on 2026-07-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsnapshot',
            name='sla_status',
            field=models.CharField(blank=True, choices=[('breached', 'Breached'), ('met', 'Met')], max_length=20, null=True),
        ),
    ]
