# Generated by Django 5.2.16 on 2026-07-29 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_ticketsnapshot_sla_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slapolicy',
            name='priority',
        ),
        migrations.AlterField(
            model_name='slapolicy',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Leave blank to apply to all departments. Fixed once the policy is created.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sla_policies', to='audit.department'),
        ),
    ]
