# Generated by Django 5.2.16 on 2026-07-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_remove_slapolicy_priority_alter_slapolicy_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketsnapshot',
            name='resolution_due_at',
        ),
        migrations.RemoveField(
            model_name='ticketsnapshot',
            name='resolution_met',
        ),
        migrations.AddField(
            model_name='ticketsnapshot',
            name='first_response_target_minutes_at_eval',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketsnapshot',
            name='follow_up_met',
            field=models.BooleanField(blank=True, help_text='True if every follow-up client message seen so far got an operator reply within target; False if any breached; null if no follow-up exchange has happened yet.', null=True),
        ),
        migrations.AddField(
            model_name='ticketsnapshot',
            name='follow_up_target_minutes_at_eval',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
