# Generated by Django 5.2.16 on 2026-07-30 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_remove_ticketsnapshot_resolution_due_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('source_type', models.CharField(choices=[('api', 'WHMCS API'), ('dump', 'DB dump upload')], default='dump', max_length=10)),
                ('whmcs_base_url', models.CharField(blank=True, max_length=255)),
                ('whmcs_api_identifier', models.CharField(blank=True, max_length=255)),
                ('whmcs_api_secret', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['project__name', 'name']},
        ),
        migrations.AlterField(
            model_name='department',
            name='whmcs_deptid',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='slapolicy',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Leave blank to apply to all departments in this project. Fixed once the policy is created.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sla_policies', to='audit.department'),
        ),
        migrations.AlterField(
            model_name='ticketsnapshot',
            name='closed_at',
            field=models.DateTimeField(blank=True, help_text='Set the first time an ingest observes status=Closed; may lag real closure by up to one sync/import interval.', null=True),
        ),
        migrations.AlterField(
            model_name='ticketsnapshot',
            name='whmcs_ticket_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='DumpUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='whmcs_dumps/')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('tickets_imported', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dump_uploads', to='audit.project')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='audit.project'),
        ),
        migrations.AddField(
            model_name='slapolicy',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sla_policies', to='audit.project'),
        ),
        migrations.AddField(
            model_name='ticketsnapshot',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='audit.project'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('project', 'whmcs_deptid')},
        ),
        migrations.AlterUniqueTogether(
            name='ticketsnapshot',
            unique_together={('project', 'whmcs_ticket_id')},
        ),
    ]
