# Generated by Django 5.2.16 on 2026-07-30 08:21

from django.conf import settings
from django.db import migrations


def backfill_dev_project(apps, schema_editor):
    Project = apps.get_model("audit", "Project")
    Department = apps.get_model("audit", "Department")
    SLAPolicy = apps.get_model("audit", "SLAPolicy")
    TicketSnapshot = apps.get_model("audit", "TicketSnapshot")

    if not (
        Department.objects.filter(project__isnull=True).exists()
        or SLAPolicy.objects.filter(project__isnull=True).exists()
        or TicketSnapshot.objects.filter(project__isnull=True).exists()
    ):
        return

    dev_project, _ = Project.objects.get_or_create(
        name="Dev",
        defaults={
            "source_type": "api",
            "whmcs_base_url": settings.WHMCS_BASE_URL,
            "whmcs_api_identifier": settings.WHMCS_API_IDENTIFIER,
            "whmcs_api_secret": settings.WHMCS_API_SECRET,
        },
    )

    Department.objects.filter(project__isnull=True).update(project=dev_project)
    SLAPolicy.objects.filter(project__isnull=True).update(project=dev_project)
    TicketSnapshot.objects.filter(project__isnull=True).update(project=dev_project)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_project_alter_department_options_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_dev_project, noop_reverse),
    ]
