# Generated by Django 5.2.16 on 2026-07-30 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0006_backfill_dev_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='audit.project'),
        ),
        migrations.AlterField(
            model_name='slapolicy',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_policies', to='audit.project'),
        ),
        migrations.AlterField(
            model_name='ticketsnapshot',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='audit.project'),
        ),
    ]
