# Generated by Django 5.2.16 on 2026-08-04 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0007_alter_department_project_alter_slapolicy_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketsnapshot',
            name='first_response_due_at',
        ),
        migrations.AlterField(
            model_name='ticketsnapshot',
            name='closed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the most recent observed closure; updates again if the ticket is reopened and closed a second time. May lag real closure by up to one sync/import interval.', null=True),
        ),
        migrations.AlterField(
            model_name='ticketsnapshot',
            name='first_response_met',
            field=models.BooleanField(blank=True, help_text='True if every client turn -- the original open and every later reopen/Customer-Reply alike -- got its first operator reply within target; False if any breached; null if none has been checked yet.', null=True),
        ),
        migrations.AlterField(
            model_name='ticketsnapshot',
            name='follow_up_met',
            field=models.BooleanField(blank=True, help_text="True if every operator turn's initial ack was followed by a final answer within target (or never grew past one message); False if any breached; null if no operator turn has happened yet.", null=True),
        ),
    ]
