# Generated by Django 5.2.16 on 2026-08-05 05:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0008_remove_ticketsnapshot_first_response_due_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whmcs_client_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='audit.project')),
            ],
            options={
                'ordering': ['project__name', 'name'],
                'unique_together': {('project', 'whmcs_client_id')},
            },
        ),
        migrations.AddField(
            model_name='ticketsnapshot',
            name='client',
            field=models.ForeignKey(blank=True, help_text="The WHMCS account this ticket's client belongs to, when known -- distinct from requestor_name, which is the often-blank per-ticket field.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='audit.client'),
        ),
    ]
