# Generated by Django 5.2.16 on 2026-08-05 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0009_client_ticketsnapshot_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
