# Generated by Django 5.2.16 on 2026-08-05 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0010_alter_client_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('done', 'Done'), ('needs_review', 'Needs review'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('model_used', models.CharField(blank=True, help_text='Snapshot of settings.OLLAMA_MODEL at run time, same _at_eval-snapshot idea sla.py uses for SLA targets -- keeps an old run reproducible even if the model setting changes later.', max_length=100)),
                ('sentiment_label', models.CharField(blank=True, choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative'), ('mixed', 'Mixed')], max_length=20)),
                ('sentiment_summary', models.TextField(blank=True)),
                ('missed_queries', models.JSONField(blank=True, default=list)),
                ('positives', models.JSONField(blank=True, default=list)),
                ('negatives', models.JSONField(blank=True, default=list)),
                ('raw_response', models.TextField(blank=True, help_text='Full Ollama reply, kept for debugging needs_review/failed rows.')),
                ('error_message', models.TextField(blank=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_audits', to='audit.ticketsnapshot')),
            ],
            options={
                'verbose_name_plural': 'AI ticket audits',
                'ordering': ['-requested_at'],
            },
        ),
    ]
