# Generated by Django 5.2.16 on 2026-08-06 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0011_ticketaudit'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whmcs_note_id', models.CharField(max_length=50)),
                ('admin_name', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField(blank=True)),
                ('posted_at', models.DateTimeField()),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_notes', to='audit.ticketsnapshot')),
            ],
            options={
                'ordering': ['posted_at'],
                'unique_together': {('ticket', 'whmcs_note_id')},
            },
        ),
    ]
