# Generated by Django 5.2.16 on 2026-08-12 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0012_ticketnote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedTicketSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('drafted', 'Drafted'), ('needs_review', 'Needs review'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('model_used', models.CharField(blank=True, help_text='Snapshot of settings.OLLAMA_MODEL at run time, same idea as TicketAudit.model_used.', max_length=100)),
                ('problem_source', models.CharField(blank=True, help_text="Short label naming the subsystem/technical area, e.g. 'Storage', 'Cloudstack'. AI-drafted, human-editable.", max_length=255)),
                ('problem_type', models.CharField(blank=True, choices=[('bug', 'Bug'), ('feature', 'Feature'), ('update', 'Update'), ('security_fix', 'Security Fix'), ('scaling', 'Scaling'), ('new_config', 'New Config'), ('ops_action', 'Ops Action')], max_length=20)),
                ('problem_root_cause', models.TextField(blank=True)),
                ('fixed_on', models.TextField(blank=True, help_text='How it was actually resolved and what was communicated back to the client.')),
                ('raw_response', models.TextField(blank=True, help_text='Full Ollama reply, kept for debugging needs_review/failed rows.')),
                ('error_message', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_closed_ticket_summaries', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='closed_summary', to='audit.ticketsnapshot')),
            ],
            options={
                'verbose_name_plural': 'Closed ticket summaries',
                'ordering': ['-queued_at'],
            },
        ),
    ]
