# Generated by Django 5.2.16 on 2026-08-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0013_closedticketsummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='use_synthetic_tid',
            field=models.BooleanField(default=True, help_text="When on, a ticket ID that doesn't already look like WHMCS's own letter-masked format (e.g. blank, or equal to the internal ticket ID) gets replaced with a generated one of the same shape. Turn this off if this project's real WHMCS ticket numbers are being incorrectly replaced -- e.g. some WHMCS installs use a distinct plain-number ticket ID that isn't masked but is still real and should be shown as-is."),
        ),
    ]
