# Generated by Django 5.2.16 on 2026-08-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0014_project_use_synthetic_tid'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='s3_access_key_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='s3_archive_enabled',
            field=models.BooleanField(default=False, help_text='When on, every reply on an eligible ticket in this project is archived to S3 as it\'s synced. Eligibility itself (ticket opened today or later, decided once the first time this project\'s sync sees the ticket) is tracked per ticket, not here -- toggling this off only stops new replies from being uploaded going forward, it does not retroactively un-mark tickets already flagged eligible, and toggling it on only covers tickets first synced after the toggle flips. Only meaningful for source_type="api" projects -- a dump import never checks this flag at all.'),
        ),
        migrations.AddField(
            model_name='project',
            name='s3_bucket_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='s3_region',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='s3_secret_access_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ticketreply',
            name='archived_to_s3_at',
            field=models.DateTimeField(blank=True, help_text="Set only after a confirmed-successful S3 upload -- the idempotency marker checked before uploading, since a ticket's replies get reprocessed from a fresh WHMCS fetch on every full refresh, not just newly-arrived ones. Null means archival was never attempted (not eligible/not enabled) or was attempted and failed; both cases are always safe to retry.", null=True),
        ),
        migrations.AddField(
            model_name='ticketsnapshot',
            name='s3_archive_eligible',
            field=models.BooleanField(default=False, help_text="True if this ticket was first observed by the WHMCS sync on the same Asia/Kolkata calendar day it was opened, AND its project had s3_archive_enabled on at that exact moment -- decided once, the first time this ticket is synced, and never recomputed afterward, so this ticket's own replies keep archiving for its whole lifecycle even once the calendar day changes. Always False for dump-imported tickets."),
        ),
    ]
