# Generated by Django 5.2.17 on 2026-09-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0015_project_s3_access_key_id_project_s3_archive_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketreply',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0, help_text="WHMCS's own 'rate this reply' 1-5 star client rating on this specific reply -- 0 means unrated (the vast majority). Not a separate table -- WHMCS stores it as a plain column alongside the rated reply itself, so this reply's own admin_name IS the tech who wrote the rated reply. WHMCS records no separate 'date the client submitted the rating' anywhere -- only this reply's own posted_at exists, so any date-filtered rating report is necessarily keyed off when the reply was POSTED, not when it was actually rated."),
        ),
    ]
