# Generated by Django 5.2.17 on 2026-09-17 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0017_projectdeletionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='escalation_analysis_enabled',
            field=models.BooleanField(default=False, help_text="When on, every non-Closed ticket in this project gets an automatic sentiment/escalation-risk analysis (TicketEscalationAnalysis) re-run every time its reply thread changes, via sync.py's own hook -- no manual trigger, no backfill of existing tickets when first turned on (only tickets that get a new reply from that point onward are analyzed)."),
        ),
        migrations.CreateModel(
            name='TicketEscalationAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('done', 'Done'), ('needs_review', 'Needs review'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('model_used', models.CharField(blank=True, help_text='Snapshot of settings.OLLAMA_MODEL at run time, same _at_eval-snapshot idea as elsewhere in this app.', max_length=100)),
                ('sentiment_category', models.CharField(blank=True, choices=[('critical', '🔴 Critical (Near Escalation)'), ('frustrated', '🟡 Frustrated (Not Happy)'), ('healthy', '🟢 Healthy (Satisfied)')], max_length=20)),
                ('escalation_risk_score', models.PositiveSmallIntegerField(blank=True, help_text='0-100 -- 0 means no risk of escalation, 100 means about to escalate/churn.', null=True)),
                ('frustration_driver', models.CharField(blank=True, choices=[('downtime', 'Downtime'), ('slow_response', 'Slow Response'), ('unresolved_technical_loop', 'Unresolved Technical Loop'), ('billing_issue', 'Billing Issue'), ('repeated_escalation', 'Repeated Escalation'), ('miscommunication', 'Miscommunication'), ('other', 'Other')], help_text="Blank only when sentiment_category is 'healthy' -- there's no frustration driver for a satisfied ticket.", max_length=30)),
                ('justification', models.TextField(blank=True, help_text='1-sentence reason for the score, drafted by the LLM.')),
                ('raw_response', models.TextField(blank=True, help_text='Full Ollama reply, kept for debugging needs_review/failed rows.')),
                ('error_message', models.TextField(blank=True)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escalation_analysis', to='audit.ticketsnapshot')),
            ],
            options={
                'verbose_name_plural': 'Ticket escalation analyses',
            },
        ),
    ]
